apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendclicker
  labels:
    app: frontendclicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendclicker
  template:
    metadata:
      labels:
        app: frontendclicker
    spec:
      containers:
        - name: frontendclicker
          image: dambott2/otelrum:1.12.0-frontendclicker
          env:
            - name: FORCE_RESTART
              value: "false"
            - name: SHOP_URL
              value: "http://my-otel-demo-frontendproxy:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontendclicker
spec:
  selector:
    app: frontendclicker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
